name: Build MXE

on:
  push:
    branches:
      - master

jobs:
  build-mxe:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Build MXE (x86)
            arch: i686
          - name: Build MXE (x64)
            arch: x86_64
    name: ${{ matrix.name }}
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y autoconf automake autopoint bash bison bzip2 cmake flex g++ g++-multilib gettext git libglib2.0-dev gperf intltool libboost-dev libc6-dev-i386 libffi-dev libgdk-pixbuf2.0-dev libltdl-dev libssl-dev libtool-bin libxml-parser-perl lzip make openssl p7zip-full patch perl pkgconf python ruby sed unzip wget xz-utils zlib1g-dev
      - name: Clone MXE Repo
        working-directory: /opt
        run: |
          sudo git clone https://github.com/mxe/mxe
      - name: Integrate libbacktrace
        working-directory: /opt/mxe
        run: |
          sudo wget https://raw.githubusercontent.com/BrettDong/MXE-GCC/master/libbacktrace.mk -P src
      - name: Build GCC 9
        working-directory: /opt/mxe
        run: |
          sudo make MXE_TARGETS=${{ matrix.arch }}-w64-mingw32.static.gcc9 MXE_PLUGIN_DIRS=plugins/gcc9 MXE_USE_CCACHE= gcc
      - name: Build libbacktrace
        working-directory: /opt/mxe
        run: |
          sudo make MXE_TARGETS=${{ matrix.arch }}-w64-mingw32.static.gcc9 MXE_PLUGIN_DIRS=plugins/gcc9 MXE_USE_CCACHE= libbacktrace
      - name: Build SDL2
        working-directory: /opt/mxe
        run: |
          sudo make MXE_TARGETS=${{ matrix.arch }}-w64-mingw32.static.gcc9 MXE_PLUGIN_DIRS=plugins/gcc9 MXE_USE_CCACHE= sdl2
      - name: Build SDL2_ttf
        working-directory: /opt/mxe
        run: |
          sudo make MXE_TARGETS=${{ matrix.arch }}-w64-mingw32.static.gcc9 MXE_PLUGIN_DIRS=plugins/gcc9 MXE_USE_CCACHE= sdl2_ttf
      - name: Build SDL2_image
        working-directory: /opt/mxe
        run: |
          sudo make MXE_TARGETS=${{ matrix.arch }}-w64-mingw32.static.gcc9 MXE_PLUGIN_DIRS=plugins/gcc9 MXE_USE_CCACHE= sdl2_image
      - name: Build SDL2_mixer
        working-directory: /opt/mxe
        run: |
          sudo make MXE_TARGETS=${{ matrix.arch }}-w64-mingw32.static.gcc9 MXE_PLUGIN_DIRS=plugins/gcc9 MXE_USE_CCACHE= sdl2_mixer
      - name: Archive MXE
        run: |
          tar -cJf mxe-${{ matrix.arch }}.tar.xz -C /opt mxe/usr
          sha256sum mxe-${{ matrix.arch }}.tar.xz
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mxe-${{ matrix.arch }}
          path: mxe-${{ matrix.arch }}.tar.xz
      - name: Install 32-bit wine
        if: ${{ matrix.arch == 'i686' }}
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine32
      - name: Install 64-bit wine
        if: ${{ matrix.arch == 'x86_64' }}
        run: |
          sudo apt install -y wine64
      - name: Verify MXE GCC
        run: |
          export PATH=/opt/mxe/usr/bin/:$PATH
          ${{ matrix.arch }}-w64-mingw32.static.gcc9-g++ -v
          cat << EOF > test.cpp
          #include <iostream>
          int main() {
            std::cout << "Hello, world!" << std::endl;
            return 0;
          }
          EOF
          ${{ matrix.arch }}-w64-mingw32.static.gcc9-g++ test.cpp -o test.exe
          wine test.exe

